name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercise1Test
      id: exercise1test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: sudo -H pip3 install pytest
    - name: Exercise3Test
      id: exercise3test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCISE1TEST_RESULTS: "${{steps.exercise1test.outputs.result}}"
        EXERCISE3TEST_RESULTS: "${{steps.exercise3test.outputs.result}}"
      with:
        runners: exercise1test,exercise3test
